### ISSUE TITLE
Create Listener to listen for special tags on weapons to increase tech tree

### ISSUE THREAD

**Issue by rourke750** [Civcraft/FactoryMod#10]
Tags applied to weapons should be listened by factory mod and apply damage to others based on what the lore tags are.

**Comment by suirad** [comment]
Close due to contraptions.

**Comment by ProgrammerDan** [comment]
Keeping it open for the moment, once contraptions is more mature I'll move all these and things like it wholesale to the contraptions repo.

**Comment by suirad** [comment]
Yea okay sounds good. I'm looking at the master issue list for the civcraft org and going through everything. I just started playing with the search to remove repos that i shouldn't need to see.

**Comment by ProgrammerDan** [comment]
Sounds good, excited to see all your work of late :)

**Comment by suirad** [comment]
Haha yea, that programming itch is back with a vengeance this time. Actually having stuff to work on for a goal keeps it going. Didn't make anything for at least 6 months before i started doing stuff here.

**Comment by ProgrammerDan** [comment]
I know those feels. I've been through so many cycles after 20+ years of coding I lost count :). But hey, I love it, and it is always there for me when I'm ready to return.

Check out codegolf on stackexchange network if you need quick programming "injections" that are fun and easy to solve, yet challenge you; it's a good way to get out of a slump.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/WurstCivTools
