### ISSUE TITLE
Compactor Documentation

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#103]
@TealNerd got it started here, can you flesh it out: https://github.com/Civcraft/FactoryMod/wiki/Compactor

**Comment by TealNerd** [comment]
Should note that compacting requires a crate and that crate is not returned
when the items are decompacted. Also The costs for the construction,
repair, and a recipe somewhere for the crate need to actually be done

**Comment by ProgrammerDan** [comment]
How is a crate acquired?

**Comment by TealNerd** [comment]
Currently no recipe, would probably be in the wood factory or something and
cost a chest + other stuff (should be pretty cheap though, maybe like a
couple pistons)

**Comment by ProgrammerDan** [comment]
Sounds like a carpentry recipe?

What did you have in mind for construction costs?

**Comment by TealNerd** [comment]
Probably some pistons, iron, redstone (to represent the stuff that's
actually smashing down the items) and then some diamonds or emeralds if it
needs to be more expensive (also maybe some crates in the contruction cost)

**Comment by ProgrammerDan** [comment]
@ttk2 Would you be opposed if I sketched out the compactor costs as Teal is describing so we can actually test the thing, but add a "Bedrock" requirement for the general compactor creation, so we can only build them on test but not be delayed in bringing these changes over to CivCraft?

**Comment by ttk2** [comment]
sounds good, make it so number one.

**Comment by ProgrammerDan** [comment]
@ttk2 so I've been plunking at this. Repair factory is uh ... well, it's rough. Haven't even gotten to compactor yet. Also a few fixes regarding recipes and other stuff that was likely missed in refactor; still working through it.

**Comment by ttk2** [comment]
Thanks a ton. Just keep me updated. If it takes a few more days it takes a
few more days.

**Comment by ProgrammerDan** [comment]
Thanks @ttk2. This is my top priority besides snitch refreshes in game, we'll get it out as soon as possible. :)

**Comment by ProgrammerDan** [comment]
BTW can I be assigned this?

**Comment by ProgrammerDan** [comment]
Docs are up. Open new issues for problems with docs.
