### ISSUE TITLE
Proposal: Compactor continues compacting or decompacting once active

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#107]
The idea would be, if you turn on compact mode it keeps compacting until either (1) there are no more full stacks of items to compact, (2) there are no crates left to use, or (3) fuel has run out.

Similarly, turning on decompact mode will keep running until either (1) there are no more items to decompact, (2) the inventory of the factory is full, or (3) fuel has run out.

Without these changes everyone is just going to emulate this behavior with complex, laggy redstone mechanisms.

That said, implementing it will add some time to finishing it up

(BUT: it will *not* impact xp/enchant pull, as compactor is staying disabled in that pull).

Thoughts?

**Comment by ttk2** [comment]
do we need compacting for repair stuff? If not disable it and keep pushing.

**Comment by ProgrammerDan** [comment]
Compactor is already disabled in config. This is for after we release everything else.

Nether Compactor does 16 stacks into 16 crates as a single action. 

General Compactor (currently) does 1 stack into 1 crate as a single action.

This is super annoying at the volumes needed for Emerald Cauldron (128 executions of General Compactor for some materials), hence this proposal. Was looking for feedback on the proposal, not inclusion/exclusion from current pull, it's staying civtest locked for now :).

**Comment by ttk2** [comment]
since we plan to go to the general compactor pretty quickly I doubt too much automation will occur.

**Comment by ProgrammerDan** [comment]
Sorry man, I must not be clear.

General Compactor *will require automation* unless I start the work described here

**Comment by ProgrammerDan** [comment]
ehh for what it's worth I think I'm going to just go ahead and do this.

Nether Compactor will go online tomorrow, it does XP ingredients only but does 16 stacks each recipe run.

General Compactor will go on in less than a week, and I'll add in this stuff so that it can run continuously. Otherwise it'd be either super tedious, or I'd have to fix the redstone bug that doesn't allow special factories to respond to Redstone input.

**Comment by ttk2** [comment]
should I update the stuff on Civtest with hlprims most recent changes?

**Comment by ProgrammerDan** [comment]
This is done. Needs testing.
