### ISSUE TITLE
Add sane error handling for invalid configs

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/FactoryMod#11]
Print readable errors and either unload the plugin or proceed with valid partial config instead of dumping the factory file

**Comment by WildWeazel** [comment]
I found a major culprit while doing logging, it explicitly does a save at the end of the load whether it succeeded or not, which seems kind of #YOLO. I mean it does ensure that it won't get stuck with an unreadable file (which doesn't take much) but at the cost of total data loss.
The larger issue of course is that's doing all this on an ordinary text file without any schema or error handling. Since we're looking at a full overhaul anyway should we just roll DB storage into that effort or try to patch up the I/O in the meantime? XML would be a decent middle ground.

**Comment by erocs** [comment]
I would love to get away from those Java serialized object files it spits out for the nether factories and printing presses. Wouldn't mind if production saves was something other then a giant CSV.

**Comment by WildWeazel** [comment]
They're all three doing poor man's serialization with a file stream >.<

**Comment by WildWeazel** [comment]
BTW I'm using a DAO factory pattern to leave it wide open for XML or SQL or whatever storage solution in the future, but for now I'm just cleaning up the IO code and pushing it behind the interface. Adding support for other formats should just be a matter of dropping in new read/write handler classes and adding a config parameter for the factory request to switch on.

**Comment by ttk2** [comment]
thanks for working this out, does this mean any changes for userland at the
moment? Or is it just better error handling in the backend.

**Comment by WildWeazel** [comment]
should be invisible to users

**Comment by WildWeazel** [comment]
related: https://github.com/gmlaxfanatic/Contraptions/issues/20

**Comment by WildWeazel** [comment]
@Valadian you still owe me a code review

**Comment by ProgrammerDan** [comment]
@WildWeazel Is this just waiting on code review?

**Comment by Valadian** [comment]
I am here. looking at it now.

**Comment by ttk2** [comment]
just holler when it needs to go on Civtest.

**Comment by ProgrammerDan** [comment]
@WildWeazel Are you satisfied that this issue is corrected with IORefactor?

**Comment by WildWeazel** [comment]
There's probably more to do especially with the yml file but I'll open new issues if I find specific problems.

**Comment by ProgrammerDan** [comment]
Yeah I had in mind just wrapping some of the calls in try/catch statements,
with clearer exception reporting, etc.
