### ISSUE TITLE
Factories destroying their output, because the chest is full

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/FactoryMod#117]
This has been discussed and on the forum before and Dan asked me to make an issue here, so there we go. Proposed solutions were to at least give a warning when starting the factory, to completly prevent it from running, if the output would take up more slots than the ones, which would be available after consuming the input or to just drop the additional items next to the chest.

**Comment by WildWeazel** [comment]
stopping the run would be safest and simplest

**Comment by ttk2** [comment]
agreed.

**Comment by ProgrammerDan** [comment]
Safest? Yes.

Simplest? Ehh... it's hard either way, bukkit exposes no "test can add"
function.

Either way, solving it within ItemStack. Compactor will use it first, we
can add it to the other things later.

**Comment by ProgrammerDan** [comment]
Well, I've got a new function testPutIn() that should be integrated into the other factory types; currently only Compactor in my latest pull is using it. However, it allows a safe way to check if adding the ItemList to the Inventory will succeed.

**Comment by ProgrammerDan** [comment]
Meant to say, assign to me. I've got code to fix this, just need to apply it.

**Comment by Maxopoly** [comment]
Fixed in new implementation
