### ISSUE TITLE
Enchantment Documentation

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#119]
The new enchantment factories need to be fully described on the wiki.

**Comment by ProgrammerDan** [comment]
Stub at: https://github.com/Civcraft/FactoryMod/wiki/Enchanting

**Comment by ProgrammerDan** [comment]
Thanks @rourke750

**Comment by ProgrammerDan** [comment]
Ok, everything is there, but dbear's writeup had a few errors that I haven't corrected yet. So I'll fix those soon, or someone else can run through and fix them.

**Comment by ttk2** [comment]
that sounds great, why not get dbear to fix them though.

**Comment by ProgrammerDan** [comment]
@dbear20 Mind cleaning the Enchantment config up? Just use the config.yml in the master branch, and look through https://github.com/Civcraft/FactoryMod/wiki/Enchanting fixing any inconsistencies. Most of the "problems" should be around repair costs.

**Comment by dbear20** [comment]
I'll try to get through that today.

**Comment by dbear20** [comment]
Ok went through everything and edited the wiki. This issue should be able to be closed now.

**Comment by ttk2** [comment]
thanks!
