### ISSUE TITLE
Production time defaults to 2

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/FactoryMod#12]
despite a comment to the contrary. This makes fuel last twice as long as you would expect if not configured. Most factories are presumably balanced to the default 2 so fixing this would involve changing the config accordingly.

**Comment by ProgrammerDan** [comment]
I can attest from the most recent round of factory additions, this causes some measure of confusion.

In general, Matta has expressed that there are two problems with nearly all existing configs:

1) Production time is too long, they need to be shortened, which leads to:

2) Fuel consumption would need rebalance against decreased production times.

Go ahead and assign this to me. I am planning to go through the config and reduce overall production times to more sensible levels, but keep stable or increase fuel consumption as appropriate.

**Comment by Maxopoly** [comment]
Not relevant after rewrite
