### ISSUE TITLE
Redstone interaction only works for Production factories (not special custom factories)

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#120]
Culprit:

https://github.com/Civcraft/FactoryMod/blame/master/src/com/github/igotyou/FactoryMod/listeners/RedstoneListener.java#L25

Redstone listener only talks to ProductionManager.

Please assign to me.

**Comment by Maxopoly** [comment]
Fixed here: https://github.com/Civcraft/FactoryMod/pull/148
