### ISSUE TITLE
Re-enabling removed blocks

### ISSUE THREAD

**Issue by Grayyer** [Civcraft/FactoryMod#121]
I'm about half way through a build, and I discovered that I can't combine 4 halfslabs into a single block. 

http://minecraft.gamepedia.com/File:Newstoneslab.png

Dan mentioned they're worse-than-removed. Which is sad.

**Comment by ttk2** [comment]
not much we can do about it unless you can turn them into a factory output.

**Comment by ProgrammerDan** [comment]
My research indicated they can't exist as inventory items. I think they best we could do was suggested as follows: Factory or recipe creates lored stone. On place, the lored stone transforms into the target placed item.

It'd be a huge pain, but it might be feasible if there's real need/desire/lust.

**Comment by ttk2** [comment]
its probably not worth the effort right now, higher priority stuff exists.

**Comment by ProgrammerDan** [comment]
Can we get a P3 or P4 on this and leave it unassigned? Someone should take a serious stab at researching where Mojang put support for these, but it's def. not high priority (sorry Gray)
