### ISSUE TITLE
Crates won't decompact

### ISSUE THREAD

**Issue by hlprimm** [Civcraft/FactoryMod#122]
If an item was compacted in the nether compactor, is it not usable in the general compactor? I bought some wheat crates from someone who presumably used the nether one, but they won't decompact. Compactor says nothing is in there.

**Comment by BlackXnt** [comment]
You have to use the nether decompactor.

**Comment by ProgrammerDan** [comment]
@hlprimm 130 diamonds in a factory to create the Nether Decompactor. If you modmail, you'll probably get the diamonds back after you've decompacted everything; at the very least, its worth the attempt. The intent was not to penalize early adopters, just when the new XP recipes were designed the designer did not anticipate General Compactor making it online so quickly.

**Comment by hlprimm** [comment]
Thanks - closing!
