### ISSUE TITLE
IronCauldron factory eats all charcoal in furnace when triggered by redstone.

### ISSUE THREAD

**Issue by kwizzlehazzizle** [Civcraft/FactoryMod#125]
If I use redstone to trigger my iron cauldron with recipe #2 (wheat, pumpkin, reeds and baked potato), the furnace will show the fire animation all the charcoal in the furnace will disappear.  No XP is produced from this.

**Comment by ProgrammerDan** [comment]
Ok. Can you give steps to reproduce?

**Comment by kwizzlehazzizle** [comment]
I'm out of materials right now so I can't check but this is basically it:
Select recipe.
Put materials in chest.
Put a stack of charcoal in furnace.
Trigger redstone pulse.

Result: 
Furnace lights up for a second.
No more coal in furnace.
No XP is created.

**Comment by ProgrammerDan** [comment]
Wicked. 

Redstone in general seems buggy on FactoryMod, but I'll add this to my pile.

**Comment by Maxopoly** [comment]
Was never confirmed/reproduced and should be fixed by rewrite even if it was a thing
