### ISSUE TITLE
Removal of old repair 

### ISSUE THREAD

**Issue by rourke750** [Civcraft/FactoryMod#126]
https://github.com/Civcraft/FactoryMod/blob/master/src/com/github/igotyou/FactoryMod/listeners/FactoryModListener.java#L502

This was a hacky fix which should really no longer be in factory mod.  All in favor of removing it.
@ttk2 @erocs @ProgrammerDan

**Comment by ttk2** [comment]
aye

**Comment by ProgrammerDan** [comment]
no harm leaving it

no harm removing it

kill it with fire

aye

**Comment by WildWeazel** [comment]
begone with it

**Comment by ProgrammerDan** [comment]
Removed by https://github.com/Civcraft/FactoryMod/pull/133
