### ISSUE TITLE
Need to disable nether conpactors

### ISSUE THREAD

**Issue by hlprimm** [Civcraft/FactoryMod#139]
Ttk asked  me to file an issue for this... What's the procedure? I can do  the pull if I have that info

**Comment by ProgrammerDan** [comment]
They are already unrepairable, so they all should have culled by now? @Ttk2

Do you mean nether decompactors?  Those are still active.

**Comment by ttk2** [comment]
Yes decompactors. Time to get those on the road to deprecation.

**Comment by ProgrammerDan** [comment]
@Hlprimm check out how i disabled repair and placement for nether compactor, should be straightforward to do to nether decompactor.

**Comment by hlprimm** [comment]
@ProgrammerDan thanks. sorry for mobile typos 
i'll get on it

**Comment by ProgrammerDan** [comment]
Solved by pull #140
