### ISSUE TITLE
Printing Presses fail with printing more than five pages

### ISSUE THREAD

**Issue by drjawa** [Civcraft/FactoryMod#14]
Printing presses in Iria, Fellowship, and other locations all seem to be non-functional.

**Comment by drjawa** [comment]
https://pay.reddit.com/r/Civcraft/comments/2pot2q/changelog_for_2014dec18/cmyx761

Essentially, trying to print more than 5 pages fails. I've updated the title of this issue. Also need a price drop as outlined in link.

**Comment by GavJenks** [comment]
I have been testing this a bunch today on civtest. I simply cannot replicate any failure of the printing press. I'm not sure this bug actually exists.

Looking at flaminius' post you linked, he just wrote "it failed" which gives me not enough information to know if he was doing something weird / user error. But I have tested at less than 5 pages, 5 pages, 10 pages, 50 pages, everything works perfectly. Multiple times, different test books, etc.

**Comment by ttk2** [comment]
Ok then. Close the bug.

**Comment by WildWeazel** [comment]
see #45

**Comment by GavJenks** [comment]
Oh, I didn't want to close this until I had tested Flaminius' parameters. He got back to me, I did, and I am now getting the same bug. I am guessing, therefore, it might have something to do with the name or content of his books. He wrote "BOOM" on every page and made the title "BOOM [# of pages]" He was also using a chest on the left side press, which I've never seen before, however, I ran into issues on civtest with both left and right versions with those book contents.

**Comment by drjawa** [comment]
Reopening. Thanks for taking the time to confirm the bug

**Comment by ProgrammerDan** [comment]
I'd love for the folks involved in this testing to re-test exactly as they did before once https://github.com/Civcraft/FactoryMod/issues/48 goes live. There's a good chance that this issue will be resolved by the fixes in #48, but if not, I'll address this separately.

My own testing post-fix on five and ten page books was success. 

However, I think the core issue is that Printing Presses give no feedback while running on the current status of the queue. I intend to address this in some upcoming code changes.

**Comment by drjawa** [comment]
Need this to be confirmed on civtest.

**Comment by ProgrammerDan** [comment]
I've done BOOM books at 5 pages, 10 pages, and 20 pages, with no issues whatsoever after the updates in https://github.com/Civcraft/FactoryMod/issues/48.

**Comment by drjawa** [comment]
Thank you very much for verifying, I'm closing this issue and putting a note in the changelog.

Excerpts from Daniel Boston's message of 2015-03-10 19:12:49 -0700:
