### ISSUE TITLE
Redstone automation does not work

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/FactoryMod#143]
All redstone related automation for factories appears to be broken.

**Comment by ProgrammerDan** [comment]
Just special factories, or Production Factories as well (e.g. "normal" recipe factories).

**Comment by ProgrammerDan** [comment]
Barring new information, appears duplicate of: https://github.com/Civcraft/FactoryMod/issues/120

**Comment by Goldmattress** [comment]
it is a duplicate, sorry

**Comment by Goldmattress** [comment]
in my defence I did ctrl+f for redstone and found nothing.

**Comment by ProgrammerDan** [comment]
No worries, happens!
