### ISSUE TITLE
Configuring Factorymod makes nothing but printing presses (Not for civcraft) ISSUE SOLVED 

### ISSUE THREAD

**Issue by darkjesusmn** [Civcraft/FactoryMod#164]
i downloaded this build of factorymod::: pastebin.com/h9bWQRAf

this build works just fine but when we go to configure it to redo some of the recipys and disable factorys with bedrock in the costs just as blackxnt and rourke told me to do because you cant delete factorys you have to disable them from being made. so i did that. i then combined recipys from other factorys to make a total of 15 factorys all redone and configed correctly as every other factory in the config is made and coded. my problem is when i try to make a factory no matter what it is it will make a printing press

heres my build of the config::: http://pastebin.com/yrDcmmnp

im not sure what i did to the config but no matter what factory i try to make, it allways makes a printing press. i could have nothing in the chest when making the factory and instead of it saying no factory was identifyed, it makes a printing press. 

so i reuploaded the orignal config to the server and tryed making anyhting besides a printing press and was able to make every factory perfectly so i tryed for a seccond time with a new config i did (i linked my copie of the config) and its making printing presses again and nothing but them.

i guess my questions are:::

1 is it even possible to reconfigre factory mod to make other factorys?

2 is it even possible to combine factory recipys? for instance the ironforge and the rail factory like i tried in my config?

3 how do i configure factorymod without having it default to making nothing but printing presses?

4 could someone look at my config and see what i missed/messed up?

**Comment by darkjesusmn** [comment]
i had someone say renaming some of the factory names to disabled may have broke it but i tryed it with the default names just now and didnt work, still makeing printing presses

**Comment by darkjesusmn** [comment]
so i just uploaded the working factorymod config and tryed to add Diamond boots to the charcoal smelter to see if i could and it made a printing press

**Comment by ProgrammerDan** [comment]
What factories do you want to be able to make? I'm assuming you have the ability to start from a fresh installation of FactoryMod; if so then you can safely rewrite the config to suite. 

Toss me your desired factory configs and I should be able to make them work for ya.

**Comment by darkjesusmn** [comment]
https://docs.google.com/document/d/1f8TBL5DXWrDIyjUzaxp8enS5GvnaJ4RXW-I9-H3jZWk/edit?ts=561734bd (sorry about the spelling, its taken us almost a month to comeup with them values and agree on them)

this is what factorys we want and the recipys we want, aswell as costs for the factorys

i wanted the repair time moved up from 28days to 90 days and all repair costs 10% of the cost to make the factory

all other factorys i wanted disabled so only the 14-15 work

if you need anything from me let me know or if you have questions on what something means in the google doc just let me know.

also ty for taking time out of your busy life to deal with my problems

**Comment by ProgrammerDan** [comment]
Just to be sure, these factory changes are for a fresh server, not an existing, running server, yes? :)

If so, I should be able to do these quickly.

**Comment by darkjesusmn** [comment]
yes sir, brand new server. we do have a test server for testing plugins before we put them on the main server (not sure if that matters) and when factory mod gets put online on the test server and all is well, it will go live on the main.

**Comment by dbear20** [comment]
http://pastebin.com/dgDSmkVE

The config you posted earlier just needed run through a yaml checker. Factorymod blows up when there is something the slightest off in the config syntax wise and there was an error or two.

In addition to fixing the errors i also removed the factories you wanted disabled. You should be able to safely remove whole factories from the config since it is for a new server, the only reason they are kept in the one for civcraft is to prevent existing factories from instantly being destroyed. The same thing goes for production recipes, i just didn't take the time to sort through them.

**Comment by darkjesusmn** [comment]
ty dbear, i checked this out just now on our test server, it works but the repair costs are much higher than i thought they were gonna be and the repair time hasnt been changed from 1 month to 3 months (TBH im not sure where to change them values or how to change them values)

i should also state this is my first time trying to work with factory mod and it confuses the hell out of me.

**Comment by darkjesusmn** [comment]
ok now after some testing more, the tool factoy and the advanced ore smelter wont change recipys

**Comment by darkjesusmn** [comment]
got it all working everyone ty dbear for checking my work and ty to ibagi for why my factorys were not changing

**Comment by ProgrammerDan** [comment]
Did you update / fix all the recipes and amounts? I've been going through them but I'll stop if you've already got it :)

**Comment by darkjesusmn** [comment]
yes sir, dbear20 has taken my config and looked into what was wrong and actually fixed my 3-4 errors in syntax i did and deleated the factorys we didnt need. supprzingly i guess i did a 3/4ths the way good job on doing my first step into trying to "code it myself" haha i did fail but not by much haha

ibagi actually helped alot aswell when some of the factorys didnt change the settings from the crafting table and that was because i forgot one recipy, the diamond shovel, i spelt it DIAMOND_SHOVEL instead of DIAMOND_SPADE lol . i didnt know it was bukket id's not mojang id's

**Comment by ribagi** [comment]
[Here is a list of all item names](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html). But sometimes you got to call a spade a spade. ;)
