### ISSUE TITLE
By default, the stone smelter repair amount is spelled wrong

### ISSUE THREAD

**Issue by Colonization** [Civcraft/FactoryMod#165]
Thought I'd pop in and let you guys know that there's a spelling mistake in the Stone Smelter. Happy Holidays to all the CivCraft devs!

    repair_inputs:
      Stone:
        material: STONE
        armount: 20

**Comment by ttk2** [comment]
does the repair still work? if so that's interesting.

**Comment by Maxopoly** [comment]
It just uses the default, which is one.

**Comment by Colonization** [comment]
Like Maxopoly said, it defaults to one. I forgot to mention, I was using the latest build at the time that I posted this.

**Comment by Maxopoly** [comment]
Not relevant anymore, because the old config wont be used anymore
