### ISSUE TITLE
Crates now require chests rather than logs to craft

### ISSUE THREAD

**Issue by Shadowcon** [Civcraft/FactoryMod#166]
I'm not sure if this is an intentional update that I just missed, but the various mass production recipes for crates now require 1248 chests rather than 1248 of the chosen log type. For clarification, I am referring to recipes such as the 864 compactor crates from dark oak logs for 1248 dark oak Logs, 64 iron using 22 charcoal from the carpentry factory.

**Comment by Maxopoly** [comment]
The recipe does actually use logs, but the description is wrong, I'm kinda surprised that it took 3 weeks for someone to notice. I'll fix it once I'm on a device that doesnt crash when I try to edit the config.


@ProgrammerDan Looks like someone was a bit too fast while copy-pasting  ;)

https://github.com/Civcraft/FactoryMod/blob/master/config.yml#L8486

**Comment by ProgrammerDan** [comment]
Who, me? ::innocent:: 

VERY likely, hah! Thanks for the report Shadowcon. Easy fix.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/FactoryMod/commit/e140b43d09e48ba31dea0219332358b353335c94
