### ISSUE TITLE
Furnace stays lit after a factory runs out of input

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/FactoryMod#171]

**Comment by Maxopoly** [comment]
No clue how to fix this, I tried so many different ways and nothing worked.

**Comment by ProgrammerDan** [comment]
Maybe for now revert back to 		
https://github.com/Civcraft/FactoryMod/blob/41d3e514c0141a66784aecfc6d3043a4a973543d/src/com/github/igotyou/FactoryMod/factories/Factory.java#L134 ?

**Comment by KillerSmurf** [comment]
@Maxopoly Fixed this issue with this PR: https://github.com/Civcraft/FactoryMod/pull/186
