### ISSUE TITLE
Factory Right-Clck for Recipe Only Works If You Go to Menu, Re-enter Recipes, then right-click

### ISSUE THREAD

**Issue by Crushtoe** [Civcraft/FactoryMod#183]
If you try to see a recipe straight out, it won't work. You have to back out to the main menu (click painting), then select show recipes, then right click.

**Comment by Maxopoly** [comment]
Yeah, because just hitting the crafting bench and then clicking a recipe is how you select a recipe for this factory, not how you get more information on it.
