### ISSUE TITLE
Usability thoughts:

### ISSUE THREAD

**Issue by ShadedJon** [Civcraft/FactoryMod#189]
Recipe page should have fuel requirement and fuel runtime.

Ingame chat alert should appear when the recipe is done. (Like it does in Gordon's factorymod)

Factory creation should trigger if you hit any of the blocks, not just the crafting table.

I'll think of some more as I fiddle more with it

**Comment by Maxopoly** [comment]
I agree on the first two, but the third one is not easily possible, because of the way the code works.

**Comment by meowcoolcat** [comment]
3rd one seems like a QOL change that really isn't needed if it takes a bunch of work to do.

**Comment by Maxopoly** [comment]
First and second are added, third one probably wont ever be fixed, so closing.
