### ISSUE TITLE
Burn_Charcoal_from_Logs_Advanced doesnt accept dark oak logs

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/FactoryMod#198]
Steps to reproduce:  

1. Select Burn Charcoal from Logs in Wood Processor
2. Put Dark Oak logs in factory chest
3. Attempt to run factory.

**Comment by Maxopoly** [comment]
That's because Minecraft is stupid. As a fix this was added: https://github.com/Civcraft/FactoryMod/blob/master/configCivcraft.yml#L862
