### ISSUE TITLE
Furnace appears to be off when unloading factory

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/FactoryMod#199]
Steps to repro:  

1. Turn on a long lasting factory  
2. Unload said factory / leave for a while / relog  
3. Check back on factory  

The factory is still running although it appears to be off.

**Comment by Maxopoly** [comment]
I've noticed this myself, it's because minecraft rechecks the burn time or something like that on chunk load/unload.

**Comment by Maxopoly** [comment]
Should be fixed by https://github.com/Civcraft/FactoryMod/commit/4851a5a7c571cf6578ce0ea9a8d1eb963853578f
