### ISSUE TITLE
Factories on public groups cannot be used by players that are not on the group

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/FactoryMod#207]

**Comment by Maxopoly** [comment]
It's using the block permission, so ofc they cant. This will be fixed as part of the permission rework by giving factory use its own permission, but for now this wont be fixed.

**Comment by BlackXnt** [comment]
You can't change permissions of non-members in public groups anyway. So the permissions rework as it is now won't fix this. For now I think you should just check if the group is public in FactoryMod.

**Comment by Maxopoly** [comment]
Solved by Permissionrework with NameLayer 2.6
