### ISSUE TITLE
Decrease aether requirement in xp recipes

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/FactoryMod#253]
I'll just start making issues here for general FM balance stuff for discussion and as TODO.

Right now it seems like Aether is the only limiting factor on xp and every pylon owner is reaching the cap with ease, so lowering the aether requirement for XP seems like the right way to go. Could probably start by lowering it by a third or something like that.

**Comment by Diet-Cola** [comment]
I think a suitable route to go would be maybe to make XP "reasonable" to create however the factory to enchant would take a long time, I've pitched this before ofcourse but it is a viable option, you shouldn't really be enchanting a prot 4 set instantly.

**Comment by Maxopoly** [comment]
I mostly agree with that suggestion, but I dont think that it solves this issue in any way.

**Comment by ProgrammerDan** [comment]
We'd also talked about adding other "direct" uses for aether -- "sinks" of a sort, but with utility.

Just depends; making XP "easier" to acquire has residual effects on the tool / prot timeline balancing, ofc.
