### ISSUE TITLE
Conside lowering XP requirements for enchanting

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/FactoryMod#255]

**Comment by Maxopoly** [comment]
Not sure whether we are actually achieving what we were aiming for with rather expensive recipes.

**Comment by Diet-Cola** [comment]
Problems with current xp:  

- Trading isn't occurring, people are stockpiling their xp to create their own tools pretty much  

Good things:  

- Towns are teaming up to effectively lower the effort required to create each factory.

**Comment by ProgrammerDan** [comment]
I definitely want to take a closer look here. Just big XP costs don't thrill me for enchanting, never have; perhaps some variety would be the key, without going overboard (28 ingredients for 1.5 stacks of X!)

**Comment by Maxopoly** [comment]
Hmm we could add a fourth XP tier, which basically combines the previous 3 paths, but basically requires entire shards to work together.

**Comment by Diet-Cola** [comment]
I think the big thing that is giving people a scare when looking at the factories is the initial setup cost & then the additional iterative cost from progressing through the tiers.

**Comment by ProgrammerDan** [comment]
Are _all_ the factories enourmously expensive to get off the ground? What's "shit-tier" and accessible? 

I really need to curl up with this and get intimate.

**Comment by Maxopoly** [comment]
The basic cauldron isnt that expensive, but the higher tiers get more expensive very fast. Same applies for the enchanting factories, though they start a bit higher. If you wanted to get back into this, I would recommend starting with jezzas spreadsheet

**Comment by Diet-Cola** [comment]
[Spreadsheet for reference](https://docs.google.com/spreadsheets/d/1K2CghpEf00R3bvtI6Ur8WWZ5gt2C4ByHgv3euEQvbFk/edit#gid=1583219349)
