### ISSUE TITLE
Allow repairing/naming items

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/FactoryMod#256]
Probably just code custom anvil functionality

**Comment by ProgrammerDan** [comment]
If someone wants to spec out what is needed, altering anvil behavior is pretty easy

**Comment by Maxopoly** [comment]
Whole thing should be enabled/disabled through a config option.

Repairing and Naming is possible through putting a repair material (emerald blocks in our case) in the second slot and the tool in the first one

Naming cost is fixed and repair cost depends on the enchants of the item and their levels. Formula for repairing cost should be hardcoded, but have multiple configurable control mechanisms.

**Comment by Maxopoly** [comment]
What's the best approach to this, listenting for itemclicks in anils?

**Comment by ProgrammerDan** [comment]
Nah, just listen for PrepareAnvilEvent - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/PrepareAnvilEvent.html

Sadly as I'm reviewing it looks like the support for Anvil control isn't as fine grained as I'd hoped. I could probably whip up some NMS stuff though, I'm getting pretty handy at that. The biggest issue I see right there is no control over "XP" cost; DENYing or cancelling the event however would just make it a big pain to use, so ideally we need to just alter the outcome as we see fit and find a way to alter the cost. 

For that we could use ItemClick event, cancel the normal pickup and spawn the item with the cost we want into inventory. Not ideal though.

**Comment by Maxopoly** [comment]
With our approach the actual vanilla xp cost would always be 0, so I guess we could either nms to set the cost to 0 or give the player exactly the xp needed in the moment he repairs/enchants.

**Comment by Maxopoly** [comment]
If we end up using NMS I would appreciate if you could do that part though.

**Comment by Maxopoly** [comment]
Implemented in WurstCivTools, so closing.
