### ISSUE TITLE
Change Pylonfinder compass price

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/FactoryMod#257]
Too many people got one too fast, it should be rare lategame tech past ST shears. Maybe make factory cheaper and recipe more expensive or completly move recipe out of factory.

**Comment by Diet-Cola** [comment]
Would be better to move out of a factory if its only going to be the compass in that factory.  

Maybe change the compass to require Aether as a time bottleneck?

**Comment by Maxopoly** [comment]
We could add Aether, but I dont think Aether should be the bottleneck. Long term we can probably find more stuff to add to that factory, but short time not.

**Comment by Diet-Cola** [comment]
Short term, putting it in one of the advanced redstone factories would be suitable enough, right now the Dowsing factory is rather pointless as your creating the factory to create 1 item that you only need 1 of.

**Comment by ProgrammerDan** [comment]
We could make it combinatory, e.g. need two or three top-tier factories before you can make it. The cost of _it_ can stay reasonable, it's just late-tech tier.

**Comment by Maxopoly** [comment]
Hmm yeah, I like the combinatory approach. Maybe include some of the drops from the mobs DJ and Akiyama made?

**Comment by ProgrammerDan** [comment]
Definitely include some drops; "thematically" might include a second tech path that leads to a lored beacon, combined with some drops that yield the compass ... something like that.
