### ISSUE TITLE
Factorymod doesn't inform player of missing materials for nether factories

### ISSUE THREAD

**Issue by drjawa** [Civcraft/FactoryMod#27]
https://www.reddit.com/r/Civcraft/comments/2r4aun/factorys_not_informing_of_required_materials/

>If you hit the crafting bench on an unmade factory, it currently states "No factory was identified". This makes it more difficult to build the factory without looking at a config and it also makes it impossible to tell whether or not you can build a nether factory in a certain area since you have no idea how many materials are actually required to build it there.
>
>fix pls
>
>To clarify:
>
>If you put each of the three aspects in a factory, and try to make the factory...Instead of telling you how many you need, it simply says the error message above.

**Comment by rourke750** [comment]
This is not an issue.  Factory mod had no way to detect what factory you
want to build unless you put in the exact required materials. Cliffs issue
was he was putting one of each aspect when the factory requires 8 of each.

**Comment by drjawa** [comment]
Ah, got it.

**Comment by ttk2** [comment]
Wasn't mattas proposed solution a command for the situation?
