### ISSUE TITLE
Why is there a Bio Lab?

### ISSUE THREAD

**Issue by ribagi** [Civcraft/FactoryMod#279]
The original Bio Lab was created to add plants and trees that were not in the map yet (Well until someone admin crimed their city some of them). The only item out of the Bio Lab and its children that you cannot get during normal game play is "Dead_Bush".

So why add a large amount of bloat to the Config?

**Comment by Maxopoly** [comment]
Just a cheap way to get all of the stuff for decoration

**Comment by Maxopoly** [comment]
Or like a lot of the other production factories to mass produce it

**Comment by ribagi** [comment]
So why can't players farm the items? They are already expected to farm other items to create the stuff in the Bio Lab.

**Comment by Maxopoly** [comment]
I'm not sure what you mean. They can manually farm those items just like they can produce them?

**Comment by ribagi** [comment]
You are requiring players to farm for Items to receive the plants for decoration, right? So why can't you require players to farm for the plants for decoration?

Additionally in the use-case where someone would want a large amount of plants for decoration most people will not use this factory simply for the cost of the factory.

**Comment by Maxopoly** [comment]
Well they can farm they manually as well, but factories are a lot more convenient, faster and cheaper. With the cost of the factory you might be right, I blame that mostly on the fact that it's too deep in the whole factory tree. The factory itself isn't that expensive, but its predecessors are what's making it not worth, so I guess we should move it somewhere else in the tree
