### ISSUE TITLE
Placeholders all over Config

### ISSUE THREAD

**Issue by ribagi** [Civcraft/FactoryMod#282]
I was making a program that parses the config into html when I noticed a number of placeholders. Sometimes they are limited to the name of the tag but most of the time it is also the output/input item.

Craft_any_type_of_fence L1670 and L1674
Craft_any_type_of_fence_gate L1682 and L1686
Craft_any_wooden_door L1694 and L1698
Craft_any_type_of_wooden_slab L1706 and L1710
Craft_any_type_of_wooden_stair L1718 and L1722
Create_poppy_advanced L2762
Kill_Dead_Bush L3587 and L3591
Kill_Dead_Shrub L3599 and L3603
Random_Priting_Press_Recipe L3855 and L3859
Take_any_mob_egg_apart L4263 and L4267
Take_friendly_mob_egg_apart_Basic L4275 and L4279

**Comment by ProgrammerDan** [comment]
Thanks, I was running into these as well

**Comment by Maxopoly** [comment]
Are those a problem? Not opposed to removing them, but I just kinda left them there as reminder for TODOs

**Comment by ribagi** [comment]
They are currently enabled, as far as I can tell, so it is kinda weird to leave them enabled.

**Comment by Maxopoly** [comment]
Oh I see, those are 1 stone for 1 stone ones, I agree that those shouldn't be enabled. We could either remove them completly or just set their type to something like PLACEHOLDER, so it'll get caught in parsing, I dont care either way.
