### ISSUE TITLE
Furnace not turning off until updated after recipe completion

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/FactoryMod#286]
Steps to repro:  

1. Run recipe  
2. Wait till recipe has finished  
3. Observe furnace 

Happened in Eilon on both the Ore Smelter & Carpentry Factory.

**Comment by MuffinPimp** [comment]
Noticed this as well.

**Comment by Maxopoly** [comment]
Seems to be fixed by the refactoring in https://github.com/Civcraft/FactoryMod/commit/2bbe117b9cdda8e374b6a47bbf60c4786efa66da
