### ISSUE TITLE
Fuel expected doesn't always equal fuel consumed

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#298]
As reported:

> I had mentioned this a couple weeks ago [...] but the recipes all seem to take less enchanting bottles than indicated on the wiki. Is the wiki just wrong? https://civfactory.github.io/devoted/#smelter Is there a different wiki to reference? Also, if you just lose the bottles and don't get any saved progress when you put in too few, why will it even run with a shortage of xp bottles?

**Comment by Maxopoly** [comment]
hmm, I'll investigate a bit

**Comment by Maxopoly** [comment]
Duplicate, closing in favor of https://github.com/Civcraft/FactoryMod/issues/276
