### ISSUE TITLE
Nerf Fish xp recipe

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#34]
too easy to bot, should also be in line with other methods of xp production in difficulty.

**Comment by ribagi** [comment]
The only reason why the other recipes are not as good as fish is only because of muster cull.  Every meat is every recipe is botable. In so it may be better to buff the other recipes.

**Comment by ttk2** [comment]
in general we have been wanting to make xp more expensive for a while,
might just use this as an excuse to adjust prices, not sure though, its
cheapness is in great part attributed to a huge amount of effort put into
making it cheap

**Comment by ribagi** [comment]
Alot of changes did happen between now and 2 years ago.  I'll get matta to help me re design xp.

**Comment by WildWeazel** [comment]
Farm-based XP was pretty terrible in hindsight, maybe this is the excuse we need to move towards more non-renewables?

**Comment by ttk2** [comment]
it did what we wanted at the end of the day, it created infrastructure.
Still better than grinder based systems

**Comment by ttk2** [comment]
now that I think about it, if we could make xp production bastion like in
its complexity it would be great, the issue is what to do with the
individual factories.

**Comment by GavJenks** [comment]
Why would you want xp made out of non renewables or significantly more expensive? Mainly all that does is make mining and building extremely more tedious with unenchanted terrible tools...?

**Comment by ttk2** [comment]
the restructuring thats needed requires a good deal more finesse than just
bumping xp prices, more discussion is required

**Comment by ProgrammerDan** [comment]
Is there a particular place this discussion is taking place? What's the best way to contribute?

**Comment by erocs** [comment]
Inactive at the moment. If you're not on the dev group list modmail an
email address to join.

**Comment by Xavter** [comment]
Since I'm still not on the dev list, if we still want to nerf the fish XP recipe we can make require another ocean animal that isn't bot-able like the other recipes. Instead of cooked fish we use squid ink. Pretty simple change and I can see the amount required(16) staying the same since you can't breed squid. Let me know if this is a stupid idea. It'd also give more incentive to live underwater ;)

**Comment by hlprimm** [comment]
Fish afk farms no longer work, at least for me. I've made a 1.8 design from YouTube but the fishing bobber doesn't get stuck  in the water.

**Comment by GavJenks** [comment]
Didn't another guy in the reddit thread say his was working fine? Are you sure it's not just an angle thing or some difference in design where one works still but one type doesn't?

**Comment by hlprimm** [comment]
It seems to vary with TPS. The problem for me is the tripwire string does
not activate when the bobber hits the water, if that narrows down the
problem. I'm going to try making a different design and report back.
http://www.reddit.com/r/Civcraft/comments/36geyq/fishing_bots_broken/

**Comment by Xavter** [comment]
No offense, but I don't think Fish AFK farms being broke for some is related to nerfing the Fish XP recipe. And since the new XP config is gonna be vegan(or so I have heard), can we close the issue?

**Comment by hlprimm** [comment]
Fish farms seem to work with a vanilla client, so I'm good.

**Comment by ProgrammerDan** [comment]
Let's closed this @ttk2 or @rourke750
