### ISSUE TITLE
Suggested improvement to Kiln.

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [Civcraft/FactoryMod#43]
Please change the Kiln recipe no.2 to...

Produce 384 Brick **blocks** (rather than individual bricks).

This will do two things: reduce the hassle of collecting the bricks and merging them into these purely aesthetic building blocks (which is a pointless time-consuming exercise) and increase output slightly which seems fairer given the difficulty of collecting the large amount of clay needed.

**Comment by ac7web** [comment]
Also it would be handy to have a recipe that takes clay blocks and turns them into brick blocks.

**Comment by Maxopoly** [comment]
Not relevant anymore, because the old config wont be used anymore
