### ISSUE TITLE
No Factory Identified

### ISSUE THREAD

**Issue by doymand** [Civcraft/FactoryMod#44]
I have a stone smelter in my house and within the past few days, it says "No factory identified". Looking through the code that error seems to be in the NetherFactoryManager createFactory method. So why that's affecting a stone smelter I have no idea.

**Comment by ttk2** [comment]
is that different from the message you would get if there was just no
factory there?

**Comment by doymand** [comment]
Apparently not actually. I guess it changed recently because it used to say "Not enough materials in chest". Though I'm fairly certain there is still some sort of problem. Even if my factory was in disrepair it has not been the required two weeks for it to completely die.I also know of another case of this happening to someone else. Their diamond pick factory stopped working in the same manner as mine but within the next day or so it was fine.

**Comment by spaceFountain** [comment]
Any new info?

**Comment by ttk2** [comment]
erocs is digging into the factory file, but its binary so he needs to write
a program to parse it

**Comment by erocs** [comment]
I'm looking at nether factories, which is separate from the other factories.

**Comment by ProgrammerDan** [comment]
Are there any other details on this issue? Is it reproducible?

**Comment by doymand** [comment]
I'm gonna put this one down to user error as even though I *think* something was wrong it may have just been my fault and I cannot reproduce it.
