### ISSUE TITLE
Neither Factory only examines the last factory within range when creating scale factor

### ISSUE THREAD

**Issue by spaceFountain** [Civcraft/FactoryMod#47]
[getScalingFactor()](https://github.com/Civcraft/FactoryMod/blob/master/src/com/github/igotyou/FactoryMod/managers/NetherFactoryManager.java#L381-L405) only returns the last factor calculated rather than the largest or the sum or some other calculation.

**Comment by WildWeazel** [comment]
Line 400 multiplies each factory into the scaling factor, that seems correct to me

**Comment by spaceFountain** [comment]
Do it does. Wops sorry about that. Boy it's much more expensive then than I even realized.
