### ISSUE TITLE
Printing Presses not producing plates

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#48]
Finally had a moment to do some serious testing on CivTest. I created multiple printing presses, four on the N-S line and four on the E-W line. Two N-S line ones are on block 0 of a chunk, two are on block 1. For each set, one is a left-handed chest configuration, and one is right-handed.

For N-S orientation, the behavior is as follows: change to set plates, put in a book & iron ingots & gold nuggets, hitting the furnace and nothing happens; hitting the chest and no status report, only the crafting table responds. This holds true for one pages books, 12 page books, unsigned books with content, but not for unsigned, empty books. I could reliably generate plates for unsigned, empty books. Any writing at all led to the described null-behavior.

Interestingly enough, setting a plate for an empty book costs no fuel, but does produce a plate. It will run without any iron or gold, or with it, equally.

The E-W factories were largely placed towards the middle of a chunk; none cross a chunk boundary.

The E-W orientation behavior was identical to N-S. In no case was I able to set plates for anything other than an empty book. Differences on E-W orientation was half were "facing" north (long edge; chests "front" is north-facing) and half "south". Within each group, 1 was left-handed, 1 right-handed.

Additionally, if the empty, unsigned book was located in the top-left of the chest, the factory would successfully produce a plate for the empty book regardless of other factory contents. In any other position when accompanied by other books, the plate setting will fail.

The factories I used on CivTest are located in -350,70,-88. They are unreinforced. I've left the books I attempted to use that replicate my books and tests in CivCraft.vg in the north-most factory, and the empty book plates in the one just south of it.

**Comment by ProgrammerDan** [comment]
A couple of additional testing updates. 

First, the plate that is generated by the empty, unsigned book, can be used to produce infinite paper. That's right, it's a duplication bug. Simply put the plate in the factory, move to Pamphlet mode, load in some paper and ink, and for every 4 ink saks get 128 pieces of paper. 

Clearly, not a valuable duplicator, but still. Interesting enough, at no point does the factory print expected costs for this empty book. If, however, you have no fuel loaded and tap the furnace, it tells you "Factory is missing fuel! (6307200 Charcoal)". So... overflow bug of some sort.

Note, Print Security Notes is a bit different. It doesn't print a cost, but takes the appropriate amounts, and produces blank pieces of paper with the plate number as flavor text (proper behavior).

Also, I tried Single Chest factory variants, and reinforced factories. Behavior is the same throughout.

**Comment by ProgrammerDan** [comment]
Last update for now: Print Books mode with the empty plate consumes fuel but not materials, and does not produce any books. Same message (missing 6307200 Charcoal) if devoid of fuel. It also doesn't print expected costs.

**Comment by ttk2** [comment]
the general agreement at this point is that the whole PrintingPress setup
needs to be recoded.

**Comment by ProgrammerDan** [comment]
Makes sense. I've been reviewing the code, and although I don't know bukkit very well, I can't discern anything obviously incorrect with the current code. Also, without being able to see the server logs, I can't tell if actions are causing exceptions. The complete and total lack of log output on dangling "else's" must be making it absolutely impossible to debug for your team.

**Comment by ProgrammerDan** [comment]
Submitted https://github.com/Civcraft/FactoryMod/pull/52 to add logging to increase issue traceability. 

Am I safe in assuming the TravisCI tool is improperly configured for this repo and its outcome can be safely ignored?

**Comment by ttk2** [comment]
yes it is improperly configured at the moment.

**Comment by ProgrammerDan** [comment]
Let me know when active on CivTest; I'll go use some presses.

**Comment by ttk2** [comment]
its up

**Comment by ProgrammerDan** [comment]
I'm low on time, but between 3:55pm and 4:00pm EST I created a factory and ran it through some tests. I'd love a paste of the server logs; not sure if I need to adjust the logging levels in the commit yet or not. The log output will let me know.

**Comment by erocs** [comment]
http://pastebin.com/m8868s5S

**Comment by ProgrammerDan** [comment]
Addressed classcast here: https://github.com/Civcraft/FactoryMod/pull/53

Working on divide by zero now. Was support for empty books (zero pages) intentional, or accidental? I can remove support if accidental.

**Comment by erocs** [comment]
Probably accidental.

**Comment by ProgrammerDan** [comment]
Cool. I'll add some checks to fail gracefully on that case.

**Comment by ProgrammerDan** [comment]
Well, graceful isn't going to be easy. Code-style wise, do you guys allow the use of RuntimeError traps to capture exceptional states? Or is that frowned upon? I'll probably have to add a trap in the BaseFactory. Or I could sidestep and just put some generic message.

**Comment by erocs** [comment]
A generic error without the trap would be best.

**Comment by ProgrammerDan** [comment]
Yeah, looking through the code further, getInputs() is used too widely; without a major refactor I'd get myself in all kinds of trouble.

**Comment by erocs** [comment]
If it has a zero page count can you just add a blank page? L544 and L624

**Comment by ProgrammerDan** [comment]
Yeah, I can do that. Thanks for the thought, was in blinders mode.

**Comment by ProgrammerDan** [comment]
Updated the pull to include new commit: https://github.com/Civcraft/FactoryMod/pull/53

I directly address the divide by zero errors in case I've missed something with adding a blank page.

Not seeing anything else to address from the prior stacktraces; lemme know if there are any issues with the pull. Otherwise, I'll look for it on Civtest.

**Comment by ProgrammerDan** [comment]
Any ETA on merging this pull? The fixes are referenced in the latest change log but have not been merged so cannot be tested.

**Comment by erocs** [comment]
http://civcraft.co:8080/job/FactoryMod-master/84/ loaded on civtest

**Comment by ProgrammerDan** [comment]
Looks good so far. I've run through single page books and empty books, behaves as expected (Empty books now create "lored" paper which cannot be used in the factory, so no duplication effect, when printing pamphlets). 

Running through a 5 page book now, then I'll do larger to test for the earlier report failure conditions (by Marcus).

**Comment by ProgrammerDan** [comment]
Five page books work fine. Ten pages works fine. Book duplication, pamphlets and security notes.

I'm going to investigate the status output when the press is actively printing or setting. It's got the least feedback yet is the most complicated to run. I'll deal with it as a separate issue.

**Comment by ttk2** [comment]
cool, should I move the current jar into prod or do you want to wrap things
up first?

**Comment by ProgrammerDan** [comment]
Your choice. If a little extra spamminess in the logs doesn't bother you,
it's safe to deploy as is. Otherwise I'll have a log level reduction pull
for you either today or tomorrow.

**Comment by ttk2** [comment]
meh it can wait

**Comment by ProgrammerDan** [comment]
As promised:

https://github.com/Civcraft/FactoryMod/pull/54

As stated, my assumption is logging level is INFO as default, so most of these logs should now cease to appear. Only the truly concerning cases will appear -- I left those as WARNING.

**Comment by ttk2** [comment]
very good, its on Civtest, after some verification of basic functionality
we can toss it online

**Comment by ProgrammerDan** [comment]
Great, I'll hop on CivTest tonight and do a controlled test, then ask for
logs from that period for a final confirm.

**Comment by ProgrammerDan** [comment]
Okay ,so from around 7:45pm to 9:45pm EST i've been testing printing presses, both on making plates and printing books (to retest Marcus's conceit). 

I had absolutely no difficulties whatsoever. I made plates for books from 1 page up to 15 pages (15 books total); no difficulty. The only note I will make is that likely, people aren't waiting long enough.  It takes a LONG time; 4 charcoal is burned per page of the book leading to a plate, and nothing leaves the chest until complete; nor is there currently any feedback on how far along the plate making is. Most folks would assume it's broken/not working, but it is. So, for books size 1 - 15, no troubles. I didn't bother with larger as the plate generation time is just too damn long.

Then, printing. I successfully made copies of every size book; there are some weird rounding anomalies with odd number page counts that make anticipating how much material will be used difficult, but otherwise it was straightforward. Again, the lack of feedback and the length of the queue being hidden from the user makes it very difficult to ascertain that the press is doing anything until books start spitting out. It will probably also not be obvious to the average user that they should never, ever turn the press off, but should let it continue until it turns itself off in every case.

So, to conclude. Plates work great, but take forever. Printing books from those plates works great, but the lack of feedback makes it painful.

Conclusion: Far as I can ascertain, all is well.

I would ask, however, that you look over the server logs for the time period listed: 7:45pm to 9:45pm, and let me know if there are any errors, or if FINE/FINER level messages are appearing in the logs.

**Comment by erocs** [comment]
I see a lot of "getPlateResult(): No book found for plate source.", but no
exceptions or errors for factorymod during this time.

**Comment by ttk2** [comment]
sounds like its good, so I should throw the jar on Civtest online?

**Comment by ProgrammerDan** [comment]
That should be safe to ignore. Checking the code, that'll pop up anytime
someone attempts to start the Set Plates mode but doesn't have a source
book in the factory.

**Comment by ttk2** [comment]
staging current civtest factorymod jar

**Comment by ProgrammerDan** [comment]
Can this be closed? PP's are working great, I've used them in Civcraft main server now as well.
