### ISSUE TITLE
Netherfactory cannot be created, does not provide error

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/FactoryMod#55]
When attempting to create a nether factory with any number of aspects  it does nothing. It doesn't tell you you can't, it doesn't make it, it just literally does nothing

**Comment by ProgrammerDan** [comment]
Is this on Civcraft, on CivTest, in the overworld, in the nether, in the end, within 5k of another NF, within exclusion zone of another NF...?

**Comment by TealNerd** [comment]
Both in the overworld with the nearest NF being at least 5k away on civtest and at least close to 5k on civcraft

**Comment by ttk2** [comment]
its exponential, close may not count.

**Comment by TealNerd** [comment]
even with scaling you can still build a factory 4k away form another and i know i'm at least that far

**Comment by ttk2** [comment]
whats the location? there might be factories you don't know about? This
should really output a factory too close message

**Comment by TealNerd** [comment]
Yeah I don't want to disclose the location so publicly but I don't think there's one nearby but even if there is it should tell me, and it should also be working on civtest but its not working there either

**Comment by ProgrammerDan** [comment]
Something truly odd must be going on, because the NetherFactoryManager has one of the best sets of else-conditions in all of FactoryMod, far as I have traced every non-exception condition will return a valid interaction response. Can you post the exact time-of-day of your last attempt? That way TTK or admin can investigate the server logs and check for exceptions?

**Comment by TealNerd** [comment]
Immediately before I opened the issue

**Comment by ttk2** [comment]
I intend to look into it, he might have to modmail info though

**Comment by ProgrammerDan** [comment]
Took me awhile, but I just created a NF in Civtest at around 11:17pm EST. No issues. First attempt I had the marker wrong; got an appropriate message. Second attempt, marker placed correctly, factory was placed without trouble. I was 5k from center of map, no scaling effects encountered.

Teal, any other circumstances or details you can provide?

**Comment by TealNerd** [comment]
reinforced all the blocks, put aspects in the chest, hit the chest with a stick, nothing happened. @ttk2  can you check the civtest logs around 5 hours ago? I was on the account Learn2Code if that helps as well

**Comment by ttk2** [comment]
2015-03-18 18:16:22 [INFO] Learn2Code issued server command: /gamemode s
2015-03-18 18:16:22 [INFO] Learn2Code: Set own game mode to SURVIVAL mode
2015-03-18 18:16:29 [INFO] Learn2Code issued server command: /tps
2015-03-18 18:16:29 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9900
-9900 -9973)
2015-03-18 18:16:39 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:39 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:39 [INFO] Learn2Code issued server command: /tps
2015-03-18 18:16:39 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:41 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:41 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:41 [INFO] FactoryMod v1.0: Factory creation attempted:
31f2f553-0338-4bc9-a8be-ee6d94d552b4 with group Learn2Code at world (-9915
-9915 -9963)
2015-03-18 18:16:48 [INFO] Learn2Code issued server command: /gamemode c
2015-03-18 18:16:48 [INFO] Learn2Code: Set own game mode to CREATIVE mode
2015-03-18 18:16:50 [INFO] Learn2Code issued server command: /tps
2015-03-18 18:17:00 [INFO] Learn2Code issued server command: /tps
2015-03-18 18:17:11 [INFO] Learn2Code issued server command: /tps

**Comment by ProgrammerDan** [comment]
Is that your actual location? Or did you modify it ttk?

**Comment by TealNerd** [comment]
that's civtest so it should be the actual location.

**Comment by ttk2** [comment]
yes its actual on civtest

**Comment by ProgrammerDan** [comment]
Ah I see, Weazel has a bug in the StringUtils, hence the odd Y values.

Truly strange. I would expect at least a message of some sort, but no exception and no interaction response on the failed factory is truly odd.

I'll look up the stack a bit for signs of exception catching that doesn't result in any kind of message. At the moment, stumped.

**Comment by TealNerd** [comment]
Figured out the issue, you apparently have to have at least 8 of each aspect to check how many you'll need. going to send a pull to check where the nearest nf is because the drama factory should be able to cause drama

**Comment by ProgrammerDan** [comment]
Damn, weird. It should still give you a "no factory found" response, or something. Not empty space.

**Comment by TealNerd** [comment]
Yeah hopefully with the new command the drama factory will actually produce some drama...

**Comment by ProgrammerDan** [comment]
Just doublechecking; is there an actionable issue here? Or is this safe to be closed out?

**Comment by ttk2** [comment]
not really sure, probably needs modmail investigation.

**Comment by jjj5311** [comment]
I think we should fix the issue with logging the location

**Comment by ProgrammerDan** [comment]
Oh yeah. Got distracted last night or there'd already be a push for it. Pretty minor fix and entirely unrelated to the issue reported here (which I believe Teal said he was able to create his factory after all, the issue is you can't "search" for a valid place to build a factory by loading less than all 8 of each aspect into the factory -- this isn't an issue, it's a feature, which is related to how the interaction manager "searches" for which factory to try to create. It has to perfectly match an existing factory definition or it simply fails).

**Comment by ttk2** [comment]
should I grab a new version from jenkins?

**Comment by ProgrammerDan** [comment]
Fix for location logging: https://github.com/Civcraft/FactoryMod/pull/58

**Comment by drjawa** [comment]
Is this on Civtest?

**Comment by ProgrammerDan** [comment]
Yeah, the X - X - Z to X - Y - Z location fix is on civtest, and is confirmed working. This issue as a whole however does not describe a bug that could be fixed, Teal was running up against the searching function for factory type; you have to have all 24 aspects minimum in the factory for it to even attempt to create a Nether Factory and give feedback of any sort. This is a core "feature" of the current FactoryMod implementation, so no bug nor change needed.
