### ISSUE TITLE
Maintainability changes

### ISSUE THREAD

**Issue by AkariAkaori** [Civcraft/FactoryMod#66]
1. Aliases for lore items

Rather than typing
```	    fuel:
	      Briquette:
	        material: COAL
	        durability: 1
	        lore: Briquette
```

in every single recipe, wouldn't it be easier to have an alias system such as this

```	    alias:
	      BRIQUETTE:
	        displayname: Briquette
	        material: COAL
	        durability: 1
	        lore: Briquette
```

Then in every instance of this item

```	    fuel:
	      Briquette:
	        alias: BRIQUETTE
```

```    inputs:
      Silicon Tetranitratobihydrotrioxycarbon:
        alias: SILICON_TETRA
      Smaragdus:
        alias: SMARAGDUS
      Rations:
        alias: BASTION_RATIONS
      Flooring:
        alias: BASTION_FLOORING
      Framing:
        alias: BASTION_FRAMING
      Objet d'art:
        alias: OBJET_DART
      Gearbox:
        alias: GEARBOX
      Base:
        alias: BASTION_BASE
      Walls:
        alias: BASTION_WALLS
```

And for other complicated setups like Bastions

2. Identifying custom items by hidden keynames rather than lore

Say in the future multilingual lore/names were to be implemented or a typo needed to be fixed, this would require a ton of refactoring for existing items, so instead of relying on lore for identification, a hidden key should be stored in the item's NBT data, which would also future proof it in case client lore editing is ever added to Minecraft

**Comment by erocs** [comment]
This would be a factory mod 2.0 request.

**Comment by ttk2** [comment]
agreed, do we have a Github Civcraft org branch for 2.0?

**Comment by rourke750** [comment]
Its Contraptions and its still in gmla repo

**Comment by ProgrammerDan** [comment]
Let's close this, related to contraptions not factorymod.
