### ISSUE TITLE
Facny Ore Smelter Bug

### ISSUE THREAD

**Issue by darkjesusmn** [Civcraft/FactoryMod#68]
found a bug with the fancy ore smelter. i put it on smelt redstone ore and it says 64 redstone ore for the input, i put 64 redstone ore in the chest and hit the furnace with the stick and it says input 64 redstone ore. there is charcoal in the furnace and there is 64 redstone ore in the chest. no clue how to fix as i do not code, and was told to put this here in the issues by the civcraft mod team

**Comment by ProgrammerDan** [comment]
Strange, the recipe as listed should require 128 redstone ore. Try putting 128 ore in the chest and seeing if the problem persists.

Reference: https://github.com/Civcraft/FactoryMod/blob/master/config.yml#L4618

**Comment by darkjesusmn** [comment]
yea it works with 128 but it still says "input 64 redstone ores" as the recipy, and thats not correct it should say 128

**Comment by ProgrammerDan** [comment]
At least it does work ;P. But I'll check it out tonight if I can.

**Comment by ProgrammerDan** [comment]
I just tested with MTA's advanced Redstone: 

http://imgur.com/jjlm7Yb

Recipe displays as expected.

Note, if you put a single stack in the chest, it'll tell you to add 64 more, if you attempt to activate the factory. Otherwise, I can't reproduce. Perhaps toss up some screenshots?

**Comment by rourke750** [comment]
Anything else or should this be closed?

**Comment by ProgrammerDan** [comment]
Probably just close, we can reopen if DJ can give me something reproducible.
