### ISSUE TITLE
Add logging for factory creation and recipie runs

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/FactoryMod#76]
Aggregate all runs of particular recipe and the creation of all factories to a text file.

**Comment by WildWeazel** [comment]
what's the need for this?

**Comment by ttk2** [comment]
stats, to know how FM is used.

**Comment by ProgrammerDan** [comment]
All creations and destructions get logged to the general log; is this topic still desired (aggregation + recipe executions?)

**Comment by ttk2** [comment]
I guess we could just bash script it from here.

**Comment by Goldmattress** [comment]
This is 100% still desired, we need to know how people use factories.

**Comment by ProgrammerDan** [comment]
I'll add it to my burndown list.

**Comment by Maxopoly** [comment]
This is also needed for my FM rewrite. What's a good way to implement a logger, any examples somewhere that I could base my thing on?

**Comment by rourke750** [comment]
Just do plugin.getLogger and use that.

**Comment by Maxopoly** [comment]
Hmm okay, thanks

**Comment by ProgrammerDan** [comment]
Agreed. I've been playing around with a lot of other structures but that seems consistently best in general. Using it, the name of the plugin is auto-matically pre-pended to the log message for you. Just reduces your complexity locally.

**Comment by Maxopoly** [comment]
Solved by rewrite
