### ISSUE TITLE
For Book & Quill, anvil-applied name is ignored when creating printing plates

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#77]
Consequently, unsigned books have no author *and* no title. Credit to SortByNode for trying this out. Probably an easy change, if this was unintended behavior; it would be nice to have "true" unattributed books that also had titles.

**Comment by WildWeazel** [comment]
you want it?

**Comment by ProgrammerDan** [comment]
Yeah. 

I've got other PP changes that I need to test, this will motivate me to do them too.

**Comment by rourke750** [comment]
@ProgrammerDan Whats the status?

**Comment by ProgrammerDan** [comment]
No change, been bouncing between too many of these things. Mostly working
on the VM tbh. I'll look at this tomorrow night most likely.

**Comment by ProgrammerDan** [comment]
Pretty sure my little commit solves this, but I am still working on getting the VM up to test, so might be a day or two. Learning puppet as I go, it's pretty syntax strict and my time is pretty strictly limited.

**Comment by Maxopoly** [comment]
Not relevant after rewrite
