### ISSUE TITLE
Mossy Cobble

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/FactoryMod#78]
Regarding pull 

https://github.com/Civcraft/FactoryMod/commit/214a04234039d76512fcbc6596e948547f81c1cb#diff-0f1be8eec416e71c28b41efb0544df26

It's WAY too late to try and fix this. At least dozens of DCs of the stuff has already been crafted by people all over civcraft (I'm not guessing that, I'm reporting at least that, probably much more), since this bug has been online for days. Not that I think anybody knew it was a bug, including myself until I saw this pull while looking up netherfactory scaling and where it is in the code. I never even would have guessed it was in factorymod at all.

The exclusivity and value of the cobble is already long gone. Turning off crafting of this right now does nothing but provide a little bit of minor unfair profit to people who happened to know about this for the last almost week or so.

It should probably simply be left online at this point.

**Comment by ttk2** [comment]
so what exactly happened, was it just not tested?

**Comment by rourke750** [comment]
No one thought of it.  We got the other stuff we just forgot this.  Anyways
this will fix it.  Just stage it.
