### ISSUE TITLE
Chain armor enchantability

### ISSUE THREAD

**Issue by TangentialThreat** [Civcraft/FactoryMod#79]
The new enchanting factory system diagram covers iron, diamond and leather but not chain armor.

**Comment by rourke750** [comment]
I feel like this is more of a question for matta/iebagi until it actually gets posted. I can't really help here.  Try message them on reddit.

**Comment by ttk2** [comment]
it does need an issue here, I asked him to make it. but yes messaging them
might help.

**Comment by Maxopoly** [comment]
Closing, because we won't be using the old config anymore.
