### ISSUE TITLE
Proposing Crystallization Factory Recipe - Water to Ice

### ISSUE THREAD

**Issue by ridgewell** [Civcraft/FactoryMod#87]
As it stands, the crystallization factory is rather useless considering the amount of block lag and relative lack thereof enchantments/rate of resources (Silk Touch & ice generation). For many cities, it has consistently been a rather frivolous factory considering the lack of recipes and limited use, and instead are traveling to use already established Crystallization factories. 

As well, the increased availability of ice *would allow for farms with low hopper counts* and **thereby increase server performance in general as a result**. This would also spur the development of alternative infrastructure such as ice roads.

I'm proposing a new crystallization factory recipe as following:

* 32 Buckets of Water for 32 Buckets, 320 Ice

A nearly full inventory of water would yield around 5 stacks of regular ice. I'm open to larger or smaller figures as well.

I'm interested in what you guys have to say about such a recipe.

**Comment by Xavter** [comment]
Uh if you make it eat the buckets I'd be for it, but otherwise this is just free ice. Why not have a vine factory? Because there's already in game mechanics for farming it. I feel like this proposal is a larger discussion on what the purpose of factorymod is than what you may have first thought.

**Comment by ridgewell** [comment]
I kept the buckets as an output because that's how the bakery recipe for cake works and it seemed appropriate to make it consistent.

**Comment by MagicalMonkey** [comment]
I've managed to farm ice in massive amounts before now by just thinking outside the box and making a cunning redstone ice-maker thing (kind of like you get in fridges). I don't think it's as big a problem as you might think. The ability to make packed ice from ice using the existing factory more than makes up for it's cost, IMHO.

**Comment by MonsieurWTF** [comment]
IF anything, it should be a 1:1 ratio of water to ice, or perhaps even 2:1. making it produce 10x the bucket size is a bit too valuable and vastly decreases the value of ice as it is.

"For many cities, it has consistently been a rather frivolous factory considering the lack of recipes and limited use, and instead are traveling to use already established Crystallization factories."

Isn't that technically a good thing that people aren't making every single factory and are using trade to take advantage of someone else's existing one?

**Comment by ttk2** [comment]
The big question is are people using hoppers rather than ice because of cost?

**Comment by MonsieurWTF** [comment]
I highly doubt it, and doesn't the lowered chunk range minimize the use of waterfall designs?

**Comment by ridgewell** [comment]
They're not using hoppers because of cost. They're using it because its available. Nobody is going to go out of their way just to harvest ice and build crystallization factories if they have iron at their dispense, making it far easier to do so.

The principle does not change. Availability means increased access to ice, and less dependence on hoppers.

**Comment by ttk2** [comment]
do you think anyone would actually switch them out though? Well maybe if it
moved items faster

**Comment by ProgrammerDan** [comment]
I don't think this has enough support to warrant inclusion, although we could reconsider it for Contraptions; I lobby this be closed unless there is a significant objection?

**Comment by rourke750** [comment]
We can leave it open for a few more days.  I need to make a reminder bot for git, oh thats what ill do next.

**Comment by ProgrammerDan** [comment]
Perhaps just open it on @WildWeazel 's Compactor fork, and close it here?

**Comment by ttk2** [comment]
Roruke if your doing frivolous stuff like that work on Portals.

**Comment by soerxpso** [comment]
@Xavter Normal ice is free ice. It's a renewable resource. The only difference between this and the current farming method is that the current method requires waiting for the water to freeze.

**Comment by ProgrammerDan** [comment]
Closing this for now. Someone remind me to reconsider this with Contraptions.
